version: "3.8"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/workspace/backend
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/workspace/frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    restart: unless-stopped
    command: ["npm", "run", "dev", "--", "--host"]

  db:
    image: "${POSTGRES_IMAGE:-postgres:15}"
    env_file:
      - ./envs/db.env
    ports:
      - "${HOST_POSTGRES_PORT:-5432}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 5s
      timeout: 5s
      retries: 12
      start_period: 5s

volumes:
  pgdata:
